name: "Commit changes and Raise PR"
description: "Commit changes to branch and raise PR"

inputs:
  github-token:
    description: 'GitHub token for creating pull requests'
    required: true
    default: ${{ github.token }}
  main-branch:
    description: 'The name of the main branch, while we slowly migrate from using master to main, default master'
    required: false
    default: 'master'

runs:
  using: composite
  steps:

  - name: Setup User Env
    shell: bash
    run: |
      git config user.name "${{ github.actor }}"
      git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

  - name: Check for changes
    shell: bash
    id: check_changes
    run: |
      if [[ -n "$(git status --porcelain)" ]]; then
        echo "has_changes=true" >> $GITHUB_OUTPUT
      else
        echo "has_changes=false" >> $GITHUB_OUTPUT
      fi

  # commit and push the changes to the branch, again the PR can't access this workspace.
  - name: Commit changes
    if: steps.check_changes.outputs.has_changes == 'true'
    shell: bash
    run: |
      git add .
      git commit -m "Update Ruby to version ${{ env.TARGET_RUBY_VERSION }}"
      git push origin ${{ env.COMMIT_BRANCH}}

  # create a draft pull request, this is because, by a github design, workflows can not trigger
  # other workflows, unless a PAT, SSH ect is used to trigger, which isn't done here, yet.
  # So to trigger workflow, just push draft to ready.
  - name: Create Pull Request
    if: steps.check_changes.outputs.has_changes == 'true'
    shell: bash
    run: |
      PR_BODY="This PR updates the Ruby version to ${{ env.TARGET_RUBY_VERSION }}.

      Changes made:
      - Updated .ruby-version file
      - Updated Dockerfile ruby version (if found)
      - Update or Rebuild Gemfile.lock (if Bundle Update failed)

      Close and reopen this PR to run the automatic checks, such as lint and test,
      as workflows can't trigger other workflows due to GitHubs imposed limitation,
      Please review and test before merging."

      gh pr create \
        --title "chore(deps): Update Ruby version to ${{ env.TARGET_RUBY_VERSION }}" \
        --body "$PR_BODY" \
        --base ${{inputs.main-branch}} \
        --head ${{ env.COMMIT_BRANCH }}\

    env:
      GH_TOKEN: ${{ inputs.github-token }}
