name: "Deprecated, please use multi env version, see readme, Check and update Ruby"
description: "Don't use this, use multi env version, see readme, Check and update Ruby"

runs:
  using: composite
  steps:
  - name: Action deprecated, please use multi env version
    id: get-ruby-version
    shell: bash
    run: |
      echo "please use multi env version"
      exit 1;
